/* generated by scripts/generate-index.mjs — do not hand-edit.
   Offline shell + visited articles. Never caches the GitHub API or user-state JSON. */
const VERSION = "pr-20260628155846";
const CORE = ["./", "index.html", "app.js?v=20260628155846", "styles.css?v=20260628155846", "favicon.svg", "manifest.webmanifest", "data/manifest.json"];

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(CORE).catch(() => {})));
});
self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});
const isStateFile = (url) => /\/data\/(reading-state|knowledge)\.json$/.test(url.pathname);
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || isStateFile(url)) return;
  const isAsset = /\.(css|js|svg|png|ico|woff2?)$/.test(url.pathname);
  if (req.mode === "navigate" || url.pathname.endsWith("/data/manifest.json") || url.pathname.includes("/articles/")) {
    e.respondWith((async () => {
      try { const fresh = await fetch(req); if (fresh && fresh.ok) (await caches.open(VERSION)).put(req, fresh.clone()); return fresh; }
      catch { return (await caches.match(req)) || (await caches.match("./")) || Response.error(); }
    })());
    return;
  }
  if (isAsset) {
    e.respondWith((async () => {
      const cached = await caches.match(req);
      const fetching = fetch(req).then((res) => { if (res && res.ok) caches.open(VERSION).then((c) => c.put(req, res.clone())); return res; }).catch(() => null);
      return cached || (await fetching) || Response.error();
    })());
  }
});
